### ISSUE TITLE
Missing `params` table

### ISSUE THREAD

**Issue by rory** [cquest/osmfr-cartocss#16]
_(Apologies for using English)_

Lots of SQL queries in this project depend on a SQL table called `params`, but it is not included, or created anywhere, and it is not documented. This table definition should be included. The queries look for several values `buffer`, `x_bleed` and `y_bleed`.

**Comment by hholzgra** [comment]
Same for the "contours" table. Looks as if the osm2pgsql instructions in the README are not correct anymore. Either a specific osm2pgsql style file needs to be used, or some extra VIEWs are needed on top of the standard style tables?

**Comment by elacour** [comment]
Seems contours may come from http://wiki.openstreetmap.org/wiki/Contours#The_PostGIS_approach

But the params table ...

**Comment by cquest** [comment]
The "contours" table is not used (its layer is disabled)

you can create an empty table with:

CREATE TABLE contours (contour geometry, ele integer);


The "params" table holds juste 3 records with the current setup for the mapnik bleed patch.

```
osm=> select * from params;
   key   | txt | num 
---------+-----+-----
 buffer  | 256 | 256
 y_bleed | 128 | 128
 x_bleed | 256 | 256
(3 rows)
```

If you use a vanilla mapnik (without this patch), I think you should set the buffer, x_bleed and y_bleed values to "0" and 0, otherwise road labels will not render on the metatile edges.
```

**Comment by cquest** [comment]
fixed by https://github.com/cquest/osmfr-cartocss/commit/25cf05ee726c0e480360bde7f7ba9470d3a3a802
